[tool.cibuildwheel]
build = "cp*"
archs = "auto64"
build-verbosity = 1
test-requires = ["pytest", "numpy"]
test-command = "pytest {package}/tests"

[tool.cibuildwheel.linux]
build = "cp*-manylinux*"
before-build = "bash tools/linux-cibuildwheel.sh"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
before-build = "bash tools/linux-cibuildwheel.sh"

[tool.cibuildwheel.windows]
before-build = "tools/windows-cibuildwheel.cmd"