[tool.cibuildwheel]
build = "*"
test-requires = ["pytest", "numpy"]
test-command = "pytest {package}/tests"

[tool.cibuildwheel.linux]
build = "cp*-manylinux*"
archs = "auto64"
before-build = "bash tools/linux-cibuildwheel.sh"
