[tool.cibuildwheel]
build = "cp310-manylinux_x86_64"
skip = ""
test-skip = ""

test-requires = ["pytest", "numpy"]
test-command = "pytest {package}/tests"

archs = ["auto"]

before-build = "bash tools/linux-cibuildwheel.sh"
