[tool.cibuildwheel]
build = "*"
archs = "auto64"
test-requires = ["pytest", "numpy"]
test-command = "pytest {package}/tests"

[tool.cibuildwheel.linux]
build = "cp*-manylinux*"
before-build = "bash tools/linux-cibuildwheel.sh"

[tool.cibuildwheel.macos]
before-build = "bash tools/linux-cibuildwheel.sh"

# [tool.cibuildwheel.windows]